name: Deploy dist
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            #   run: |
            #     echo "cloning repo.."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: '20'
