name: Build the React App
on: [push,workflow_dispatch]
jobs:
    Run_Test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: '20'
            - name: Version of Node .js
              run: node -v
            - name: Install Dependences
              run: npm ci 
            - name: Run Test
              run: npm test
    Deploy:
        needs: Run_Test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: '20'
            - name: Install Dependences
              run: npm ci 
            - name: Build Project
              run: npm run build
            - name: Deploy
              run: echo "Deploying to production server..."